# Using pandas dataframes
This notebook demonstrates how to load data into a pandas dataframe and do basic operations with the dataframe data.

## Loading BB3 Cruise data into a pandas df

In [6]:
# === using `import ... as ...`
# you can import pandas as usual
import pandas
# and use it
print(f"pandas.__version: {pandas.__version__}")

# but people often give pandas another name - `pd` when imported
# to do this you can use `import ... as ...`
import pandas as pd
# now we can make the same code more succinct
print(f"pd.__version__: {pd.__version__}")

# pd and pandas are exactly the same *object*.
print("pd =?= pandas")
print(f"{pd == pandas}")

# if we add something to the pd object
pd.my_randomly_named_attribute = "This is Tylar's special string object"
# the two objects are still equal
print(f"Did adding the attribute change `pd` but not `pandas`? {pd == pandas}")
# we can use the attribute we put on `pd` on the `pandas`
print(f"pandas.my_randomly_named_attribute: {pandas.my_randomly_named_attribute}")

# you can even import it again with a different name
import pandas as whatever_i_feel_like
print(f"whatever_i_feel_like.__version__: {whatever_i_feel_like.__version__}")
# and the new import is still the exact same object as `pd` and `pandas`
print(f"whatever_i_feel_like.my_randomly_named_attribute: {pandas.my_randomly_named_attribute}")
# You can get creative with this but... please don't.
# Stick to the original name or common usages like `pandas as pd`
# Another common one is `numpy as np`
import numpy as np
print(f"np.__version__: {np.__version__}")
# and xarray
import xarray as xr
print(f"xr.__version__: {xr.__version__}")

pandas.__version: 1.3.3
pd.__version__: 1.3.3
pd =?= pandas
True
Did adding the attribute change `pd` but not `pandas`? True
pandas.my_randomly_named_attribute: This is Tylar's special string object
whatever_i_feel_like.__version__: 1.3.3
whatever_i_feel_like.my_randomly_named_attribute: This is Tylar's special string object
np.__version__: 1.21.2

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/cfgrib_.py:28: UserWarning: Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. Try `import cfgrib` to get the full error message
  "Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. "

xr.__version__: 0.19.0

In [8]:
# Loading Sat data into pandas (is df the right data structure for this?)
import os

import pandas
from IPython.display import display

FILEPATH = "../../data/WS19266_BB3.raw"

# read the tab-separated-values file (`.raw` = `.tsv`)
bb3_df = pandas.read_csv(
    FILEPATH, 
    sep='\t',
    on_bad_lines='skip',  # default is 'error'. can also use 'warn' and 'skip'
    # usecols=["date","time","470nm", "470nm_data","532nm", "532nm_data", "650nm", "650nm_data", "mystery_column"],
    skiprows=1
)

# now you can use the pandas dataframe
SEPARATOR = "="*302  # this creates big string like `=====================` with 302 `=` characters
display(bb3_df.describe())
display(SEPARATOR)
display(bb3_df.info())
display(SEPARATOR)
display(bb3_df)

,470,2153,532,2043,650,4130,536
count,3.090500e+04,3.078400e+04,3.063000e+04,3.047700e+04,3.027000e+04,3.006100e+04,29786.000000
mean,1.333423e+03,3.012149e+03,1.561360e+03,1.326214e+03,9.365565e+02,1.918062e+03,528.212348
std,5.442526e+04,2.408126e+05,6.211511e+04,3.077109e+04,3.776643e+04,3.476398e+04,599.449778
min,0.000000e+00,-2.680000e+02,0.000000e+00,-2.049000e+03,0.000000e+00,-2.670000e+02,-65.000000
25%,4.700000e+02,1.260000e+02,5.320000e+02,1.510000e+02,6.500000e+02,1.820000e+02,517.000000
50%,4.700000e+02,3.050000e+02,5.320000e+02,3.850000e+02,6.500000e+02,5.220000e+02,521.000000
75%,4.700000e+02,1.040000e+03,5.320000e+02,1.106000e+03,6.500000e+02,3.761000e+03,524.000000
max,4.704130e+06,4.130413e+07,5.324130e+06,4.130130e+06,6.503842e+06,4.134130e+06,52521.000000

'=============================================================================================================================================================================================================================================================================================================='

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31073 entries, 0 to 31072
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   07/29/19  31056 non-null  object
 1   12:06:15  31007 non-null  object
 2   470       30905 non-null  float64
 3   2153      30784 non-null  float64
 4   532       30630 non-null  float64
 5   2043      30477 non-null  float64
 6   650       30270 non-null  float64
 7   4130      30061 non-null  float64
 8   536       29786 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.1+ MB

None

'=============================================================================================================================================================================================================================================================================================================='

       07/29/19  12:06:15    470    2153    532    2043    650    4130    536
0      07/29/19  12:06:16  470.0  2151.0  532.0  2034.0  650.0  4130.0  536.0
1      07/29/19  12:06:17  470.0  2121.0  532.0  1994.0  650.0  4130.0  535.0
2      07/29/19  12:06:18  470.0  2119.0  532.0  1992.0  650.0  4130.0  535.0
3      07/29/19  12:06:19  470.0  2117.0  532.0  1991.0  650.0  4130.0  535.0
4      07/29/19  12:06:20  470.0  2115.0  532.0  1993.0  650.0  4130.0  535.0
...         ...       ...    ...     ...    ...     ...    ...     ...    ...
31068  09/29/19  05:10:20  470.0  2045.0  532.0  1537.0  650.0  4130.0  519.0
31069  09/29/19  05:10:21  470.0  1405.0  532.0  1480.0  650.0  4130.0  519.0
31070  09/29/19  17:36:11  470.0   120.0  532.0    87.0  650.0   853.0  527.0
31071  09/29/19  17:36:12  470.0   121.0  532.0    79.0  650.0   847.0  526.0
31072       etx       NaN    NaN     NaN    NaN     NaN    NaN     NaN    NaN

[31073 rows x 9 columns]

## Loading sat image data into pandas

In [1]:
import pandas
FILEPATH =  "../../data/MODA_OC_py_data/A2007143182500.L2_LAC_OC.x.nc"

# The xarray library handles arbitrary-dimensional netCDF data, and retains metadata. 
# Xarray provides a simple method of opening netCDF files, and converting them to pandas dataframes.
import xarray

# create an xarray.Dataset from `.nc` file
img_dataset = xarray.open_dataset(FILEPATH)

# Here we use `display()` instead of `print()` to get a prettier output.
# (You can't do this outside of a jupyter notebook.)
from IPython.display import display
display(img_dataset)

# but the xr.DataSet breaks when we try to convert it to a dataframe.
# uncomment the next line and try it yourself:
img_df = img_dataset.to_dataframe()  # throws `ValueError: no valid index for a 0-dimensional object`

# === convert the `xr.Dataset` to a `pandas.DataFrame`
# this file has a hierarchy of groups so it is more complicated than just using
# `img_dataset.to_dataframe()` as usual.
# [SO q/a ref](https://stackoverflow.com/a/54813257/1483986)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/cfgrib_.py:28: UserWarning: Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. Try `import cfgrib` to get the full error message
  "Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. "
/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/plugins.py:61: RuntimeWarning: Engine 'cfgrib' loading failed:
Cannot find the ecCodes library
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
Attributes: (12/50)
    title:                             HMODISA Level-2 Data
    product_name:                      A2007143182500.L2_LAC_OC.nc
    processing_version:                2018.0
    equatorCrossingLongitude:          96.08638
    orbit_number:                      26876
    history:                           l2gen par=/data3/sdpsoper/vdc/vpu6/wor...
    ...                                ...
    geospatial_lon_max:                -75.57883
    geospatial_lon_min:                -90.01822
    startDirection:                    Ascending
    endDirection:                      Ascending
    day_night_flag:                    Day
    earth_sun_distance_correction:     0.9754039645195007

In [20]:
!FILEPATH="../../data/MODA_OC_py_data/A2007143182500.L2_LAC_OC.x.nc"
!ncdump -h $FILEPATH

/bin/bash: ncdump: command not found

In [11]:
FILEPATH =  "../../data/MODA_OC_py_data/A2007143182500.L2_LAC_OC.x.nc"

import xarray
from IPython.display import display

# TODO: figure out how to get group names from within python
NC_GROUP_TO_OPEN = "geophysical_data"  # get this using bash `ncdump -h` or similar
LAT_LON_GROUP = "navigation_data"

img_dataset = xarray.open_dataset(FILEPATH, group=NC_GROUP_TO_OPEN)
print(img_dataset.variables)
display(img_df)

img_df = img_dataset.to_dataframe()

# now you can use the pandas dataframe
display(img_df.describe())
# print("="*302)

Frozen({'aot_869': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Aerosol optical thickness at 869 nm
    standard_name:  atmosphere_absorption_optical_thickness_due_to_ambient_ae...
    valid_min:      0
    valid_max:      30000, 'angstrom': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Aerosol Angstrom exponent, 443 to 865 nm
    standard_name:  aerosol_angstrom_exponent
    valid_min:      -30000
    valid_max:      5000, 'Rrs_412': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 412 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1711.8177, 'Rrs_443': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 443 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1887.5414, 'Rrs_469': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 469 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  2035.2333, 'Rrs_488': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 488 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1941.784, 'Rrs_531': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 531 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1859.4445, 'Rrs_547': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 547 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1869.9834, 'Rrs_555': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 555 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1837.5674, 'Rrs_645': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 645 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1587.4379, 'Rrs_667': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 667 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1524.3859, 'Rrs_678': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:         Remote sensing reflectance at 678 nm
    units:             sr^-1
    standard_name:     surface_ratio_of_upwelling_radiance_emerging_from_sea_...
    valid_min:         -30000
    valid_max:         25000
    solar_irradiance:  1481.3671, 'chlor_a': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Chlorophyll Concentration, OCI Algorithm
    units:          mg m^-3
    standard_name:  mass_concentration_chlorophyll_concentration_in_sea_water
    valid_min:      0.001
    valid_max:      100.0
    reference:      Hu, C., Lee Z., and Franz, B.A. (2012). Chlorophyll-a alg...
    keywords:       EARTH SCIENCE > OCEANS > OCEAN CHEMISTRY > CHLOROPHYLL, 'chl_ocx': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Chlorophyll Concentration, OC3 Algorithm
    units:          mg m^-3
    standard_name:  mass_concentration_chlorophyll_concentration_in_sea_water
    valid_min:      0.001
    valid_max:      100.0
    reference:      O'Reilly, J.E., and 24 Coauthors, 2000: SeaWiFS Postlaunc...
    keywords:       EARTH SCIENCE > OCEANS > OCEAN CHEMISTRY > CHLOROPHYLL, 'Kd_490': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Diffuse attenuation coefficient at 490 nm, KD2 algorithm
    units:          m^-1
    standard_name:  diffuse_attenuation_coefficient_of_downwelling_radiative_...
    valid_min:      50
    valid_max:      30000, 'pic': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Calcite Concentration, Balch and Gordon
    units:          mol m^-3
    standard_name:  mole_concentration_of_particulate_inorganic_carbon_in_sea...
    valid_min:      -32500
    valid_max:      30000
    reference:      Balch, W.M., Gordon, H.R., Bowler, B.C., Drapeau, D.T., a..., 'poc': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Particulate Organic Carbon, D. Stramski, 2007 (443/555 ve...
    units:          mg m^-3
    standard_name:  mole_concentration_of_particulate_organic_carbon_in_sea_w...
    valid_min:      -32000
    valid_max:      -27000
    reference:      Stramski, D., et al. "Relationships between the surface c..., 'ipar': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Instantaneous Photosynthetically Available Radiation
    units:          einstein m^-2 s^-1
    standard_name:  downwelling_photosynthetic_photon_radiance_in_sea_water, 'nflh': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:  Normalized Fluorescence Line Height
    units:      W m^-2 um^-1 sr^-1
    valid_min:  -32353
    valid_max:  32353
    reference:  Behrenfeld, M.J., Westberry, T.K., Boss, E.S., O'Malley, R.T...., 'par': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=float32]
Attributes:
    long_name:      Photosynthetically Available Radiation, R. Frouin
    units:          einstein m^-2 day^-1
    standard_name:  surface_downwelling_photosynthetic_photon_flux_in_air
    valid_min:      -32750
    valid_max:      32250
    reference:      Frouin, R., Ligner, D.W., and Gautier, C., 1989: A Simple..., 'l2_flags': <xarray.Variable (number_of_lines: 1353, pixels_per_line: 664)>
[898392 values with dtype=int32]
Attributes:
    long_name:      Level-2 Processing Flags
    valid_min:      -2147483648
    valid_max:      2147483647
    flag_masks:     [          1           2           4           8         ...
    flag_meanings:  ATMFAIL LAND PRODWARN HIGLINT HILT HISATZEN COASTZ SPARE ...})

                                 aot_869  angstrom   Rrs_412   Rrs_443  \
number_of_lines pixels_per_line
0               0                    NaN       NaN       NaN       NaN
                1                    NaN       NaN       NaN       NaN
                2                    NaN       NaN       NaN       NaN
                3                    NaN       NaN       NaN       NaN
                4                    NaN       NaN       NaN       NaN
...                                  ...       ...       ...       ...
1352            659                  NaN       NaN       NaN       NaN
                660               0.1375    1.1466  0.011616  0.009384
                661               0.1367    1.1405  0.011764  0.009504
                662               0.1346    1.1340  0.011930  0.009582
                663               0.1338    1.1096  0.011718  0.009448

                                  Rrs_469   Rrs_488   Rrs_531   Rrs_547  \
number_of_lines pixels_per_line
0               0                     NaN       NaN       NaN       NaN
                1                     NaN       NaN       NaN       NaN
                2                     NaN       NaN       NaN       NaN
                3                     NaN       NaN       NaN       NaN
                4                     NaN       NaN       NaN       NaN
...                                   ...       ...       ...       ...
1352            659                   NaN       NaN       NaN       NaN
                660              0.008146  0.006490  0.002674  0.001822
                661              0.008098  0.006662  0.002708  0.001874
                662              0.008210  0.006742  0.002798  0.001948
                663              0.008132  0.006698  0.002784  0.001944

                                  Rrs_555   Rrs_645  ...   Rrs_678   chlor_a  \
number_of_lines pixels_per_line                      ...
0               0                     NaN       NaN  ...       NaN       NaN
                1                     NaN       NaN  ...       NaN       NaN
                2                     NaN       NaN  ...       NaN       NaN
                3                     NaN       NaN  ...       NaN       NaN
                4                     NaN       NaN  ...       NaN       NaN
...                                   ...       ...  ...       ...       ...
1352            659                   NaN       NaN  ...       NaN       NaN
                660              0.001416 -0.000050  ...  0.000126  0.080205
                661              0.001432 -0.000014  ...  0.000150  0.079811
                662              0.001452  0.000008  ...  0.000160  0.081086
                663              0.001468 -0.000022  ...  0.000162  0.083306

                                  chl_ocx  Kd_490       pic        poc  \
number_of_lines pixels_per_line
0               0                     NaN     NaN       NaN        NaN
                1                     NaN     NaN       NaN        NaN
                2                     NaN     NaN       NaN        NaN
                3                     NaN     NaN       NaN        NaN
                4                     NaN     NaN       NaN        NaN
...                                   ...     ...       ...        ...
1352            659                   NaN     NaN       NaN        NaN
                660              0.077388  0.0278  0.000012  34.000000
                661              0.079689  0.0278  0.000022  34.600098
                662              0.084455  0.0288  0.000044  36.000000
                663              0.086358  0.0290  0.000040  36.399902

                                     ipar      nflh        par    l2_flags
number_of_lines pixels_per_line
0               0                     NaN       NaN        NaN  1074790936
                1                     NaN       NaN        NaN  1074790936
                2                     NaN       NaN        NaN  1074790936
                3                     NaN       NaN        NaN  1074790936
                4                     NaN       NaN        NaN  1074790936
...                                   ...       ...        ...         ...
1352            659                   NaN       NaN  60.484001  1610613536
                660              0.002093  0.012460  60.571999   536871200
                661              0.002094  0.038470  60.549999   536871200
                662              0.002095  0.051730  60.604000   536871200
                663              0.002097  0.049095  60.672001   536870944

[898392 rows x 21 columns]

,aot_869,angstrom,Rrs_412,Rrs_443,Rrs_469,Rrs_488,Rrs_531,Rrs_547,Rrs_555,Rrs_645,...,Rrs_678,chlor_a,chl_ocx,Kd_490,pic,poc,ipar,nflh,par,l2_flags
count,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,87628.000000,...,87628.000000,87604.000000,87556.000000,87617.000000,44964.000000,87608.000000,87628.000000,79188.000000,218457.000000,8.983920e+05
mean,0.195771,0.893121,0.009778,0.008267,0.007764,0.006362,0.002780,0.002070,0.001676,-0.000040,...,0.000202,0.208140,0.181997,0.033976,0.000811,46.941074,0.002049,0.114106,56.967770,1.058904e+09
std,0.084263,0.411226,0.003130,0.002406,0.002271,0.002412,0.002639,0.002560,0.002345,0.000463,...,0.000351,1.225809,1.229010,0.084339,0.003873,62.733784,0.000034,0.110101,4.294397,1.400481e+08
min,0.008800,-0.152200,-0.004886,-0.004868,-0.004682,-0.004862,-0.004286,-0.004196,-0.004910,-0.006830,...,-0.006556,0.001511,0.001000,0.016600,0.000012,0.199707,0.001890,-0.483260,0.743996,0.000000e+00
25%,0.119700,0.538800,0.007486,0.006600,0.006450,0.005124,0.001628,0.001018,0.000750,-0.000256,...,0.000048,0.066973,0.032221,0.018400,0.000014,23.000000,0.002034,0.053005,56.416000,1.073743e+09
50%,0.190300,0.800300,0.009082,0.007770,0.007505,0.006084,0.002280,0.001570,0.001218,-0.000096,...,0.000140,0.099953,0.058755,0.023600,0.000076,29.600098,0.002050,0.105960,58.239998,1.074791e+09
75%,0.259400,1.181900,0.012132,0.009834,0.008754,0.007048,0.002884,0.002086,0.001676,0.000082,...,0.000274,0.141229,0.125688,0.034200,0.000230,45.399902,0.002070,0.155685,59.192001,1.074791e+09
max,0.484700,2.147400,0.032446,0.027920,0.032310,0.034136,0.028008,0.025212,0.022602,0.012668,...,0.011154,217.868942,217.868942,6.400000,0.130534,5652.200195,0.002113,4.904295,61.619999,1.616429e+09

## GEE data into dataframe

In [ ]:
# TODO: cp from https://mygeoblog.com/2017/01/13/your-gee-data-in-pandas/

## streaming sat data from `rio-tiler` into dataframe

In [13]:
# TODO: is there an easy way to get from data loaded using `rio-tiler` into a `pandas.dataframe`?